### ISSUE TITLE
align repo naming with ausdigital

### ISSUE THREAD

**Issue by onthebreeze** [test-point/test-point.github.io#10]
This org contains the reference implementations and test suites for all ausdigital implementations.  As such the repo names should be clearly traceable to the corresponding ausdigital specification and each should have a consistent subdirectory structure.  

Please note the ticket at https://github.com/ausdigital/ausdigital.github.io/issues/19 

Please create a testpoint repository with the same name as the corresponding ausdigital specification repo.  eg "dcl" will contain the reference implementation and test suite for the dcl specification.

* testpoint repo name = spec name (eg "dcl")
* testpoint repo title = "<spec full name> reference implementation and test suite" (eg "digital capability locator reference implementation and test suite"
* test point repo web URL will link to <spec>.testpoint.io if the service is implemented and to "testpoint.io/<spec>" if it's still in construction.
* each repo will contain the following sub-directories:
  * /src-<tech>/ for the service implementation - eg /src-py or /src-js
  * /client-<tech>/ for any client implementations - eg /client-js
  * /docs/ for the technical documentation to support building services or client.
  * /tests/ for the executable test suite - both gherkin code and anu generated docs.

Lets create all the repos - but where code does not yet exist then just say so in the readme.md.   Make sure the readme.md for every repo links to all the docs and tests and live end points and reference ausdigital spec accordingly.

**Comment by onthebreeze** [comment]
Slight update - lets call the testpoint repos "testpoint-foo".   A similar convention [is agreed](https://github.com/ausdigital/ausdigital.github.io/issues/19) for ausdigital specs ("ausdigital-foo"). 

Rationale - as a developer I may want local copies of both the ausdigital spec and the testpoint implementation and it would be confusing if they had the same local name.  So "ausdigital-foo" and "testpoint-foo" works nicely.

**Comment by kshychko** [comment]
repositories have been added/updated with README,md, LICENSE and COPYING files

**Comment by monkeypants** [comment]
Is this done @kshychko ?

**Comment by kshychko** [comment]
yes, from the repositories naming and structure perspective

**Comment by monkeypants** [comment]
> Lets create all the repos - but where code does not yet exist then just say so in the readme.md. Make sure the readme.md for every repo links to all the docs and tests and live end points and reference ausdigital spec accordingly.

And this? I'm asking if I can close this ticket.

**Comment by kshychko** [comment]
missed this point, let me update the README.md files

**Comment by kshychko** [comment]
the README.md files have bee updated, i think the ticket can be closed now.
