### ISSUE TITLE
refactor testpoint.io website page.md -> html via jekyll

### ISSUE THREAD

**Issue by onthebreeze** [test-point/test-point.github.io#11]
We need to refactor the testpoint.io website which is currently a mix of github hosted html (for pages like testpoint.io/foo) and some similar looking pages on active testpoint services (for pages like foo.testpoint.io).  

What we need is a nice jekyll generated testpoint website that has a homepage like http://testpoint.io/ and then a set of specification specific sub-pages like http://testpoint.io/foo - where there is a "foo" for every spec (idp, dcl, dcp, tap, tap-gw, nry, json, code, bill).  

Each sub-page will have a similar template - like http://testpoint.io/tap where we need to be able to edit (via simple foo.md page) 

* title
* description
* link to image
* table with bullets on left and a panel on right for each bullet.

**Comment by onthebreeze** [comment]
much the same framework (but obviously different templates) as used at ausdigital.org

**Comment by monkeypants** [comment]
This ticket is still open because of menu links to foo.testpoint.io, which should be to testpoint.io/foo.html

**Comment by onthebreeze** [comment]
Also - after reviewing the first iteration, I think it's better to "un-roll" that table of tabs/links at the bottom of each testpoint.io/foo page.  Instead it shoiuld just be a single page of HTML generated from a single foo.md page in https://github.com/test-point/test-point.github.io/tree/master/pages

Simpler to manage and simpler to navigate.

**Comment by monkeypants** [comment]
in the unrolled version of the page, the current menu items can become subheadings. This will give us room for more words.

**Comment by monkeypants** [comment]
I think we can close this @onthebreeze
