### ISSUE TITLE
Wrong links

### ISSUE THREAD

**Issue by krylataya** [test-point/test-point.github.io#15]
DCP page:
Wrong link "Support is available through the GitHub site." Should be https://github.com/ausdigital/ausdigital-dcp
Bill page:
Wrong link to API specification https://app.swaggerhub.com/api/ausdigital/ausdigital-syn/1.0.0

**Comment by kshychko** [comment]
fixed, please verify

**Comment by krylataya** [comment]
Issue fixed.
