### ISSUE TITLE
services > test SMP

### ISSUE THREAD

**Issue by monkeypants** [test-point/test-point.github.io#6]
this menu item should actually link to https://smp.testpoint.io

the label should be "metadata-publisher"

**Comment by monkeypants** [comment]
SMP page (skin for actual working SMP API)

Heading says 

```
A TESTPOINT.IO METADATA PUBLISHER TEST SERVICE
```

should be

```
Metadata Publisher
```

**Comment by monkeypants** [comment]
text at top of page says

```
B2B frameworks may leverage multiple providers of identity with varying degrees of identity
confidence, The higher the identity integrity, the lower the rist associated with B2B transactions
and the lower the cost of services such as trade financing. This test service simulates various
OIDC providers and scopes.
```

should say:

Implementation of the the SMP component. suitable for non-production use by developers adopting [AusDigital open standards](http://ausdigital.github.io/).

**Comment by monkeypants** [comment]
remove the dummy Companybook advertisement from the page. (this is something we might want to put back one day)

**Comment by monkeypants** [comment]
The bit that says

```
AVAILABLE IODC IDP TEST RESOURCES
```

should say

```
Resources
```

Under it, the menu widget thing that has "identity" and "relying party" LH menu items, should have:
- API
- Data Fixtures
- Test User Accounts
- UI

When API is selected, the well on the right should:
- link to the swaggerhub spec
- explain many resources do not require authentication, but update and identity management features do.
- link to docs at https://metadata-publisher.readthedocs.org/)
- invite users to contribute to the spec development at https://github.com/ausdigital/metadata-publisher

When the Data Fixtures is selected, the well on the right should:
- say "coming soon..."
- explain that "Developers will soon be able to authenticate to testpoint.io using a test version of the VanGuard Business to Government (B2G) identity provider. Until now, this canonical Australian Business Identity system has been exclusively reserved for Government Departments. This innovation will provide a higher level of business identity assurance than has previously been possible in B2B systems in Australia".

When Test User Accounts is selected, the well on the right should:
- Explain that developers can authenticate to https://idp.testpoint.io/ using a GitHub credential, and use this session to claim administrative control over Australian Businesses in the test SMP. They can use their administrative control over claimed businesses to set credentials in idp.testpoint.io for those businesses, and then use these credentials through the API (and UI) in a testing context.
- explain that only one developer (github account) can claimed a business; there are millions to chose from, if you don't take more than you need for testing purposes there should be plenty for everybody.

When UI is selected, the well on the right should contain a react widget with full faceted search/browse capability, etc.

**Comment by koriaf** [comment]
Partially done on idp.testpoint.io; please review and update any dumb text remaining
