### ISSUE TITLE
jekyll fixes - SMP->DCP

### ISSUE THREAD

**Issue by monkeypants** [test-point/test-point.github.io#7]
we need to rename SMP to DCP.

please:
 * [x] fix jekyl sub-site to dcp.testpoint.io (from smp.testpoint.io)
 * [x] fix all links everywhere in testpoint.io to the dcp URL
 * [x] fix the content on the SMP page (heading, text, etc)

**Comment by webilhan** [comment]
@monkeypants Replaced all SMP to DCP. Created for DCP separate page and markdown files. But link https://dcp.testpoint.io/ doesn't work. Could you configure?

**Comment by monkeypants** [comment]
@onthebreeze; the current links to smp.testpoint.io need to change. Either redirect to a dcp.testpoint.io test endpoint OR testpoint.io/dcp.html if there is no endpoint.

So now is a good time to decide if we make a DCP.testpoint.io (reference implementation) or just link to test.companybook.io (which would need to exist, etc), and maybe also link to that free OASIS SMP java thing. We did talk about making a free/reference SMP in the past, which is a reduced version of companybook, but I think it's a complication we could do without.

I propose we:
 * offer test.companybook.io as the testing endpoint
 * reference test.companybook.io (and OASIS SMP thing) from the /dcp.html
 * consider publishing test artefacts (which pass against test.companybook.io, etc)

**Comment by onthebreeze** [comment]
better I think to us dcp.testpoint.io.  Companybook is a commercial venture and should remain separated from the free testpoint as that service ausdigital.org

**Comment by monkeypants** [comment]
Ok, so we make DCP.testpoint.io that is equivalent to test.companybook.io (except totally separate branding).

**Comment by koriaf** [comment]
related service is working now.

**Comment by monkeypants** [comment]
Is this all done?
