### ISSUE TITLE
diagram - fix SMP->DCP

### ISSUE THREAD

**Issue by monkeypants** [test-point/test-point.github.io#8]
re: #7, we also need to fix the diagrams so they say
```
Test DCP
(Metadata
Publisher)
```
(not "Test SMP..."). This is for all versions of the diagrams.

**Comment by onthebreeze** [comment]
"Capability Publisher" ,  not "Metadsta Publisher"

**Comment by monkeypants** [comment]
Are you sure? The two word phrase we have been using consistently is "metadata publisher" (repo name, read the docs URL).

**Comment by fritzelemino** [comment]
Hi @monkeypants and @onthebreeze ,

All diagrams are updated already. Please here:

Homepage?
https://www.dropbox.com/s/rnowg451i178fgc/Homepage%20diagram.png?dl=0

Subpages
https://www.dropbox.com/sh/wh4q7bnavtun49b/AABrhguqq7lJO9QlXj1DpSMma?dl=0

Subpages mobile
https://www.dropbox.com/sh/s33e03rxhw94vc4/AADGT4k77CJOk5KOPQxyt6uta?dl=0

Let me know if you have more changes to these diagrams

Regards,

**Comment by fritzelemino** [comment]
Hi @monkeypants  and @onthebreeze , please check the updated files here:

https://www.dropbox.com/sh/3cfrt57c0949ve4/AACpoTw9pmP8UQolXc2a31YFa?dl=0

Thank you 

Regards,

**Comment by monkeypants** [comment]
it's all good now, thanks.
