### ISSUE TITLE
stand up dcp.testpoint.io

### ISSUE THREAD

**Issue by monkeypants** [test-point/test-point.github.io#9]
we need dcp.testpoint.io (was formerly smp.testpoint.io) per #7

**Comment by koriaf** [comment]
The basic migration is done.
http://dcp.testpoint.io/api/v0/businesses?format=json
@onthebreeze

**Comment by koriaf** [comment]
Will we rename https://app.swaggerhub.com/api/ausdigital/metadata-publisher/1.0 to digital-capability-publisher?
I can replace "Service Metadata Publisher" to "Digital Capability Publisher" and "SMP" to "DCP" in this file, but I think whole API renaming requires @onthebreeze intervention.

**Comment by monkeypants** [comment]
I see the API seems to work, but the page here http://dcp.testpoint.io/ still has "SMP" language.

I agree about fixing swaggerhub too. It would also be nice if GitHub was source of the spec published to swaggerhub.

**Comment by koriaf** [comment]
The github is not a source, but some kind of backup storage. Swaggerhub pushes current API after each save to github.

wording updated. wording in code still uses SMP, but it's quite extensive improvement to change the code this way, so let's assume it as a low-priority task.

**Comment by koriaf** [comment]
Can we close it?
